### ISSUE TITLE
Percy forever waiting on snapshot to be uploaded

### ISSUE THREAD

**Issue by MondeSameWave** [percy/percy-cli#2]
Building a ember 2.5 app. Testing with travis with parallel test suits. I've configured pretender to let percy through `this.post('/_percy/:path', this.passthrough);` and added the environment variable `PERCY_PARALLEL_TOTAL=2` in travis. 

I've only added one snapshot to a test. All tests pass on travis but percy is hanging.
The "Waiting for snapshot uploads... " message is displayed.

**Comment by fotinakis** [comment]
If you run your tests locally with `ember test --server` do you see any console error messages?

**Comment by MondeSameWave** [comment]
@fotinakis This is not the correct repo to report my issue. moving it to https://github.com/percy/ember-percy/issues/5
