### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by BevanR** [percy/percy-cli#3]
I'd like to know what coverage Percy tests are giving me.  Is there any way I can do this?  Is it a feature request?

**Comment by fotinakis** [comment]
Can you elaborate a bit more on what you're looking for? Do you mean you want to see how much of your app your Percy's visual tests cover?

**Comment by BevanR** [comment]
Exactly.  I'd like to know which lines of JavaScript are _not_ get executed by any of the tests.

**Comment by fotinakis** [comment]
So, for "lines of JavaScript" you should look into https://codecov.io/, Percy only does visual coverage.

**Comment by BevanR** [comment]
Thanks for the quick response @fotinakis.

I had a go getting codecov.io working, but I don't understand how it can integrate with Percy;

- Does Percy output a code coverage file?  Where?
- How do I get Codecov to parse Percy's code coverage file?

(I'm using Circle CI, but would happily switch.)

At this early stage I only have Percy tests.  I don't have any unit, integration, e2e or behaviour tests.

I want to know which lines of JavaScript code are _not_ being executed by Percy's screenshot bot, so that I can create more tests to cover those bits of code (possibly not Percy tests).

**Comment by fotinakis** [comment]
Interesting feature request! Percy does not do any sort of code coverage right now, but that's a potentially cool integration we could do with codecov. I'll put it on our list of feature requests.

**Comment by BevanR** [comment]
Great!  Thanks!  What's the best way for me to be notified if/when you complete this?

**Comment by fotinakis** [comment]
We would likely announce that large of a feature on blog.percy.io and our twitter account (https://twitter.com/percy_io).
